language: elixir

elixir: 1.10.0

otp_release: 22.0

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

services:
  - redis-server

script:
  - MIX_ENV=test mix do ecto.create, ecto.load, test --exclude external:true

sudo: false
dist: trusty
